src/api/CarnivoreIDApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView  # TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("caidapp/", include("caidapp.urls")),
    path("accounts/", include("allauth.urls")),  # <--
    path("accounts/", include("allauth.socialaccount.urls")),  # <--
    path("", RedirectView.as_view(url="/caidapp/")),  # <--I
    # path("", TemplateView.as_view(template_name="caidapp/login.html"), name="login"),  # <--I
]

if settings.DEBUG_TOOLBAR:

    # urlpatterns = [
    #     *urlpatterns,
    # ] + debug_toolbar.debug_toolbar_urls()
    urlpatterns = [
        # path("__debug__/", include(debug_toolbar.urls)),
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    print(f"{urlpatterns=}")

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# print (static(settings.MEDIA_URL))
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/api/caidapp/urls.py
from django.urls import include, path

# from rest_framework import routers
from django.views.generic import DetailView

from . import (
    models,
    views,
    views_admin,
    views_general,
    views_locality,
    views_mediafile,
    views_uploads,
)


def trigger_error(request):
    """Trigger an error for Sentry testing purposes."""
    division_by_zero = 1 / 0
    return division_by_zero


# router = routers.DefaultRouter()
# router.register(r"localities", views.LocalitiesViewSet)


app_name = "caidapp"
urlpatterns = [
    path("", views.login, name="index"),
    path("djangologin/", views.MyLoginView.as_view(), name="djangologin"),
    path("logout/", views.logout_view, name="logout_view"),
    path("user_settings/", views.CaIDUserSettingsView.as_view(), name="update_caiduser"),
    # path("rest_api/", include(router.urls)), # not used any more
    path("workgroup-invitations/create/", views.WorkGroupInvitationCreateView.as_view(), name="workgroup_invitation"),
    path("workgroup-invitations/", views.WorkGroupInvitationListView.as_view(), name="workgroup_invitations"),
    path("workgroup-invitations/for_user/", views.WorkGroupInvitationForUserListView.as_view(), name="workgroup_invitations_for_user"),
    path("workgroup-invitations/<int:pk>/", views.WorkGroupInvitationDetailView.as_view(), name="workgroup_invitation_detail"),
path(
    "workgroup-invitations/<int:pk>/accept/",
    views.WorkGroupInvitationAcceptView.as_view(),
    name="workgroup_invitation_accept",
),

path(
    "workgroup-invitations/<int:pk>/decline/",
    views.WorkGroupInvitationDeclineView.as_view(),
    name="workgroup_invitation_decline",
),

    path("upload/", views.upload_archive, name="upload_archive"),
    # path("user_settings/", views.update_caiduser, name="update_caiduser"),
    path(
        "upload/contains_single_taxon/",
        views.upload_archive,
        {"contains_single_taxon": True},
        name="upload_archive_contains_single_taxon",
    ),
    path(
        "upload/contains_identities/",
        views.upload_archive,
        {"contains_identities": True, "contains_single_taxon": True},
        name="upload_archive_contains_identities",
    ),
    # path("login/", TemplateView.as_view(template_name="caidapp/login.html"), name="login"),
    # Uploads
    path("uploads/", views.uploads_species, name="uploads"),
    path("uploads_identities/", views.uploads_identities, name="uploads_identities"),
    path("uploads_known_identities/", views.uploads_known_identities, name="uploads_known_identities"),
    path(
        "uploadedarchive_mediafiles/<int:uploadedarchive_id>",
        # views.uploadedarchive_mediafiles,
        views.media_files_update,
        name="uploadedarchive_mediafiles",
    ),
    path(
        "uploadedarchive_detail/<int:uploadedarchive_id>",
        # views.uploadedarchive_mediafiles,
        views_uploads.uploadedarchive_detail,
        name="uploadedarchive_detail",
    ),
    # path("media_files/", views.media_files, name="media_files"),
    path(
        "<int:uploadedarchive_id>/delete_upload/<str:next_page>/",
        views.delete_upload,
        name="delete_upload",
    ),
    path(
        "update_uploadedarchive/<int:uploadedarchive_id>/",
        views.update_uploadedarchive,
        name="update_uploadedarchive",
    ),
    path(
        "<int:uploadedarchive_id>/run_processing/",
        views.run_taxon_classification,
        name="run_processing",
    ),
    path(
        "<int:uploadedarchive_id>/run_taxon_classification_force_init/",
        views.run_taxon_classification_force_init,
        name="run_taxon_classification_force_init",
    ),
    path("refresh_data/", views.refresh_data, name="refresh_data"),
    # Localities
    path("manage_localities/", views_locality.manage_localities, name="manage_localities"),
    path("delete_locality/<int:locality_id>/", views_locality.delete_locality, name="delete_locality"),
    path(
        "update_locality/<int:locality_id>/",
        views_locality.update_locality,
        name="update_locality",
    ),
    path(
        "update_locality/",
        views_locality.update_locality,
        name="update_locality",
    ),
    path("taxon/<int:taxon_id>", views.media_files_update, name="taxon"),
    # Media Files
    path("media_files/", views.media_files_update, name="media_files"),
    path(
        "mediafile/<int:pk>/update/",
        views_mediafile.MediaFileUpdateView.as_view(),
        name="media_file_update",
    ),
    # path(
    #     "media_file_update/<int:media_file_id>/",
    #     views_mediafile.media_file_update,
    #     name="media_file_update",
    # ),
    path(
        "media_files/locality/<str:locality_hash>",
        views.media_files_update,
        name="media_files_locality",
    ),
    path(
        "representative_mediafiles/",
        lambda request: views.media_files_update(request, identity_is_representative=True),
        name="representative_mediafiles",
    ),
    path(
        "individual_identity_mediafiles/<int:individual_identity_id>",
        views.media_files_update,
        name="individual_identity_mediafiles",
    ),
    path(
        "delete_mediafile/<int:mediafile_id>/",
        views.delete_mediafile,
        name="delete_mediafile",
    ),
    path(
        "observation/<int:pk>/delete/",
        views_mediafile.ObservationDeleteView.as_view(),
        name="observation_delete",
    ),
    # Albums
    path("albums/", views.albums, name="albums"),
    path("album/<str:album_hash>", views.media_files_update, name="album"),
    path("album_update/<str:album_hash>/", views.album_update, name="album_update"),
    path("delete_album/<str:album_hash>/", views.delete_album, name="delete_album"),
    path("new_album/", views.new_album, name="new_album"),
    # Identity
    path("identities/export_csv", views.export_identities_csv, name="export_identities_csv"),
    path("identities/export_xlsx", views.export_identities_xlsx, name="export_identities_xlsx"),
    path("identities/import", views.import_identities_view, name="import_identities"),
    path(
        "individual_identity_create/",
        views.individual_identity_create,
        name="individual_identity_create",
    ),
    path(
        "individual_identity_create/media_file/<int:media_file_id>",
        views.individual_identity_create,
        name="individual_identity_create",
    ),
    # path(
    #     "individual_identity_update/<int:individual_identity_id>",
    #     views.individual_identity_update,
    #     name="individual_identity_update",
    # ),
    path(
        "individual_identity_update/<int:pk>",
        views.IndividualIdentityUpdateView.as_view(),
        name="individual_identity_update",
    ),
    path(
        "individual_identity/share/<str:identity_hash>",
        views.shared_individual_identity_view,
        name="shared_individual_identity",
    ),
    path(
        "delete_individual_identity/<int:individual_identity_id>",
        views.delete_individual_identity,
        name="delete_individual_identity",
    ),
    # path(
    #     "individual_identities/",
    #     views.individual_identities,
    #     name="individual_identities",
    # ),
    path(
        "individual_identities/",
        views.IdentityListView.as_view(),
        name="individual_identities",
    ),
    path("dash_identities/", views.dash_identities, name="dash_identities"),
    path("init_identification/", views.init_identification_view, name="init_identification"),
    path("train_identification/", views.train_identification, name="train_identification"),
    path("stop_init_identification/", views.stop_init_identification, name="stop_init_identification"),
    path(
        "run_identification/<int:uploadedarchive_id>/",
        views.run_identification_view,
        name="run_identification",
    ),
    path(
        "run_identification_on_unindentified/",
        views.run_identification_on_unidentified,
        name="run_identification_on_unidentified",
    ),
    path(
        "get_individual_identity_zoomed/<int:foridentification_id>/<int:reid_suggestion_id>",
        views.get_individual_identity_zoomed,
        name="get_individual_identity_zoomed",
    ),
    path(
        "get_individual_identity_zoomed_by_identity/<int:foridentification_id>/<int:identity_id>",
        views.get_individual_identity_zoomed_by_identity,
        name="get_individual_identity_zoomed_by_identity",
    ),
    path(
        "get_individual_identity_zoomed_paired_points/<int:foridentification_id>/<int:reid_suggestion_id>",
        views.get_individual_identity_zoomed_paired_points,
        name="get_individual_identity_zoomed_paired_points",
    ),
    path(
        "get_individual_identity/",
        views.get_individual_identity_from_foridentification,
        name="get_individual_identity",
    ),
    path(
        "get_individual_identity/<int:foridentification_id>",
        views.get_individual_identity_from_foridentification,
        name="get_individual_identity",
    ),
    path(
        "get_individual_identity/media_file/<int:media_file_id>",
        views.get_individual_identity_from_foridentification,
        name="get_individual_identity_by_media_file",
    ),
    path(
        "remove_foridentification/<int:foridentification_id>",
        views.remove_foridentification,
        name="remove_foridentification",
    ),
    path(
        "set_individual_identity/" + "<int:mediafiles_for_identification_id>/<int:individual_identity_id>",
        views.set_individual_identity,
        name="set_individual_identity",
    ),
    path(
        "not_identified_mediafiles/",
        views.not_identified_mediafiles,
        name="not_identified_mediafiles",
    ),
    path("show_log/", views.show_log, name="show_log"),
    path("show_taxons/", views.show_taxons, name="show_taxons"),
    # path(
    #     "workgroup_update/<str:workgroup_hash>/",
    #     views.workgroup_update,
    #     name="workgroup_update",

src/api/caidapp/templates/caidapp/albums.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
{% endblock %}
{% block body %}
    {% if user.is_authenticated %}

        <div class="pagetitle">
            <h1>{{ page_title }}</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploads' %}">Uploads</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <section class="section">
        <div class="row" id="row-of-cards">

        {% if albums %}
            {% for album in albums %}
                <div class="col-xl-3">
                {#                        <div class="col" style="-ms-flex: 0 0 200; flex: 0 0 200;">#}
                <div class="card"
                        {% if album.mediafiles.all.0 %}
                     style="

                             background-image: linear-gradient(to left, rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 1.0)), url({{ album.mediafiles.all.0.thumbnail.url }});
                             background-repeat: no-repeat;
                             background-position-x: right;
                             background-position-y: center;
                             background-size: cover;
                             "

                        {% endif %}
                >
                    <div class="card-body"
                    >
                        <h5 class="card-title">{{ album }}</h5>
                        {#                        <p>Status: {{ album.mediafiles.0.thumbnail.url }} </p>#}
                        <p>Created At: {{ album.created_at|date:'Y-m-d H:i' }} </p>
                        <p>{{ album.description }} </p>

                        {#                    <p><i class="fa-light fa-calendar-image"></i>Uploaded at: {{ uploadedarchive.uploaded_at|date:'Y-m-d H:i' }} </p>#}
                        {#                    {% if uploadedarchive.finished_at %}#}
                        {#                        <p>Finished at: {{ uploadedarchive.finished_at|date:'Y-m-d H:i' }} </p>#}
                        {#                    {% endif %}#}
                        {##}
                        <a class="btn btn-primary"
                           href="{% url 'caidapp:album' album.hash %}">
                            <i class="bi bi-images"></i> Detail
                        </a>
                        <a class="btn btn-secondary"
                           href="{% url 'caidapp:album_update' album.hash %}">
                            <i class="bi bi-images"></i> Edit
                        </a>
                    </div>
                </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% endif %}
{% endblock %}

src/api/caidapp/templates/caidapp/generic_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <h2>{{ view.title|default:"Detail" }}</h2>
    {% include "caidapp/include_breadcrumb_nav.html" %}
  <div class="card my-3">
    <div class="card-body">
      <dl class="row">
        {% for f in fields %}
          <dt class="col-sm-3">{{ f.verbose_name|capfirst }}</dt>
          <dd class="col-sm-9">{{ f.value }}</dd>
        {% endfor %}
      </dl>
    </div>
  </div>

  <a href="{{ view.cancel_url|default:'/' }}" class="btn btn-secondary">{% trans "Back" %}</a>
    {% if bottom_button_list %}
        {% for button in bottom_button_list %}
            <a href="{{ button.url }}" class="btn btn-{{ button.style|default:"primary" }}">{{ button.label }}</a>
        {% endfor %}
    {% endif %}
{% endblock %}

src/api/caidapp/templates/caidapp/generic_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
<h2>{{ view.title|default:"Form" }}</h2>
    {% include "caidapp/include_breadcrumb_nav.html" %}
    <p>
    {{ description }}
    </p>
<form method="post">
    {% csrf_token %}
            {{ form|crispy }}
    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
    <a href="{{ view.cancel_url|default:'/' }}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
</form>
{% endblock %}

src/api/caidapp/templates/caidapp/generic_include_filter.html
{% load i18n %}
{% load custom_tags %}
{% load crispy_forms_tags %}

{% if filter %}
    <form method="get" class="filter-form d-flex align-items-end flex-wrap gap-2">
        {{ filter.form|crispy}}
        <button type="submit" class="btn btn-secondary h-100 align-self-end mb-3" >
            <span class="bi bi-search"></span>
                {% trans 'Filter' %}
        </button>
    </form>
{% endif %}

src/api/caidapp/templates/caidapp/generic_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load custom_filters %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {{ form.media }}
    <!-- Include jQuery -->

{% endblock %}

{% block body %}
    {#<div class="container">#}
    {% if user.is_authenticated %}
        <div class="pagetitle">
            <h1>{{ view.model | get_verbose_name_plural }}</h1>
            <nav>
{#                <ol class="breadcrumb">#}
{#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploads' %}">Uploads</a></li>#}
{#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploadedarchive_mediafiles' mediafile.parent.id %}"> Uploaded#}
{#                        Archive: {{ mediafile.parent }}</a></li>#}
{#                </ol>#}
            </nav>
        </div><!-- End Page Title -->
        <div class="section">
            <div class="row">
            {% for object in object_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ object }}</h5>
                            <ul class="list-group list-group-flush">
{#                                {% for field in view.model. %}#}
{#                                    {% if not field.auto_created and not field.primary_key %}#}
{#                                        <li class="list-group-item">#}
{#                                            <strong>{{ field.verbose_name }}:</strong> {{ object|getattr:field.name }}#}
{#                                        </li>#}
{#                                    {% endif %}#}
{#                                {% endfor %}#}
                            </ul>
                            <a href="{% url view.get_detail_url_name pk=object.pk %}" class="btn btn-primary mt-3">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        </div>
    {% endif %}
    {#</div>#}
{% endblock %}

src/api/caidapp/templates/caidapp/generic_list_cards.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load custom_filters %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {{ form.media }}
    <!-- Include jQuery -->

{% endblock %}

{% block body %}
    {#<div class="container">#}
    {% if user.is_authenticated %}
        <div class="pagetitle">
            <h1>{{ view.model | get_verbose_name_plural }}</h1>
            <nav>
{#                <ol class="breadcrumb">#}
{#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploads' %}">Uploads</a></li>#}
{#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploadedarchive_mediafiles' mediafile.parent.id %}"> Uploaded#}
{#                        Archive: {{ mediafile.parent }}</a></li>#}
{#                </ol>#}
            </nav>
        </div><!-- End Page Title -->
        <div class="section">
            <div class="row">
            {% for object in object_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ object }}</h5>
                            <ul class="list-group list-group-flush">
{#                                {% for field in view.model. %}#}
{#                                    {% if not field.auto_created and not field.primary_key %}#}
{#                                        <li class="list-group-item">#}
{#                                            <strong>{{ field.verbose_name }}:</strong> {{ object|getattr:field.name }}#}
{#                                        </li>#}
{#                                    {% endif %}#}
{#                                {% endfor %}#}
                            </ul>
                            <a href="{% url view.get_detail_url_name pk=object.pk %}" class="btn btn-primary mt-3">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        </div>
    {% endif %}
    {#</div>#}
{% endblock %}

src/api/caidapp/templates/caidapp/get_individual_identity_zoomed_paired_points.html
{% extends "caidapp/get_individual_identity_zoomed_base.html" %}
{% block inner_block %}

                        <div class="row" id="row-of-cards">

{#                       Unknown image#}
{#                            <div class="{{ col_style }} me-5" id="card{{ mediafile.id }}">#}
{#                                <div class="card">#}
{#                                    <img class="card-img-top" src="{{ foridentification.mediafile.mediafile.url }}"#}
{#                                         alt="Camera trap">#}
{#                                </div>#}
{#                            </div>#}

{#                    Top N #}
                            <div class="{{ col_style }}" id="card{{ mediafile.id }}">
                                <div class="card">
                                    <img class="card-img-top"
                                         alt="Camera trap"
                                         src=
                                    {% if html_img_src %}

                                                    {% autoescape off %}
                                                        {{ html_img_src }}
                                                    {% endautoescape %}
                                    {% endif %}
                                    >
                                    <div class="card-body">
                                        <div class="card-title">
                                            Top-{{ reid_suggestion_index|add:1 }}: {{ top_name }}
                                        </div>
                                        <p class="card-text">
                                            {{ top_score|floatformat:2 }}
                                        </p>
                                        <p class="card-text">
                                            {% if top_mediafile.identity %}
                                                <a href="{% url 'caidapp:set_individual_identity' foridentification.id top_mediafile.identity.id %}"
                                                   class="btn btn-primary">Select</a>
                                            {% else %}
                                                Identity does not exist
                                            {% endif %}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
{% endblock %}

src/api/caidapp/templates/caidapp/identity_detail_public.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block head %}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>#}
    <script>
        function copyToClipboard() {
            const dummy = document.createElement('input');
            const text = window.location.href;

            document.body.appendChild(dummy);
            dummy.value = text;
            dummy.select();
            document.execCommand('copy');
            document.body.removeChild(dummy);

            alert('URL copied to clipboard: ' + text);
        }
    </script>
    <!-- Include jQuery -->

{% endblock %}

{% block body %}
    {#<div class="container">#}
    {% if user.is_authenticated %}
        <div class="pagetitle">
            <h1>{{ identity.name }}</h1>
            <nav>
                <button  class="btn btn-primary" onclick="copyToClipboard()">
                    <i class="fas fa-link"></i>
                    Copy URL</button>
{#                <ol class="breadcrumb">#}
{#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploads' %}">Uploads</a></li>#}
{#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploadedarchive_mediafiles' mediafile.parent.id %}"> Uploaded#}
{#                        Archive: {{ mediafile.parent }}</a></li>#}
{#                </ol>#}
            </nav>
        </div><!-- End Page Title -->
        <div class="container">
            <p><strong>Name:</strong> {{ identity.name }}</p>
            <p><strong>Code:</strong> {{ identity.code }}</p>
            <p><strong>Juvenile Code:</strong> {{ identity.juv_code }}</p>
            <p><strong>Sex:</strong> {{ identity.get_sex_display }}</p>
            <p><strong>Coat Type:</strong> {{ identity.get_coat_type_display }}</p>
            <p><strong>Workgroup</strong> {{ identity.owner_workgroup }}</p>

        </div>
        <div class="section">
            <div class="row">
                {% for mediafile in mediafiles %}
                <div class="col-md-6">
                    <img src="{{ mediafile.thumbnail.url }}" alt="Image" class="img-fluid">
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {#</div>#}
{% endblock %}

src/api/caidapp/templates/caidapp/individual_identity.html
{% extends 'base.html' %}

{% block body %}
    {#<div class="container">#}
    {% if user.is_authenticated %}
        <div class="pagetitle">
            <h1>{{ headline }}</h1>
            <nav>
                <ol class="breadcrumb">
                    {#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploads' %}">Uploads</a></li>#}
                    {#                    <li class="breadcrumb-item"><a href="{% url 'caidapp:uploadedarchive_detail' mediafile.parent.id %}"> Uploaded#}
                    {#                        Archive: {{ mediafile.parent }}</a></li>#}
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <div class="section">
            <div class="row" id="row-of-cards">
                <div class="col-lg-3" id="card{{ mediafile.id }}">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                Unknown
                            </div>
                            <p class="card-text">
                            </p>
                        </div>
                        <img class="card-img-bottom" src="{{ foridentification.mediafile.mediafile.url }}"
                             class="card-img-bottom" alt="Camera trap image">
                    </div>
                </div>
            </div>
            <div class="row" id="row-of-cards">
                <div class="col-lg-3" id="card{{ mediafile.id }}">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                {{ foridentification.top1name }}
                            </div>
                            <p class="card-text">
                                {{ foridentification.top1score }}
                                <a href="{% url 'caidapp:get_individual_identity' %}" class="stretched-link"> </a>
                            </p>
                        </div>
                        <img class="card-img-bottom" src="{{ foridentification.top1mediafile.mediafile.url }}"
                             class="card-img-bottom" alt="Camera trap image">

                    </div>
                </div>
                <div class="col-lg-3" id="card{{ mediafile.id }}">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                {{ foridentification.top2name }}
                            </div>
                            <p class="card-text">
                                {{ foridentification.top2score }}
                                <a href="{% url 'caidapp:get_individual_identity' %}" class="stretched-link"> </a>
                            </p>
                        </div>
                        <img class="card-img-bottom" src="{{ foridentification.top2mediafile.mediafile.url }}"
                             class="card-img-bottom" alt="Camera trap image">
                    </div>
                </div>
                <div class="col-lg-3" id="card{{ mediafile.id }}">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                {{ foridentification.top3name }}
                            </div>
                            <p class="card-text">
                                {{ foridentification.top3score }}
                                <a href="{% url 'caidapp:get_individual_identity' %}" class="stretched-link"> </a>
                            </p>
                        </div>
                        <img class="card-img-bottom" src="{{ foridentification.top3mediafile.mediafile.url }}"
                             class="card-img-bottom" alt="Camera trap image">
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {#</div>#}
{% endblock %}

src/api/caidapp/templates/caidapp/manage_locations.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
{% endblock %}
{% block body %}
    {% if user.is_authenticated %}
    <div class="pagetitle">
        <h1>Manage Localities</h1>
    </div>
        <section class="section">
        <form method="POST">
            <div class="form-group">
            {% csrf_token %}
{#            {{ page_obj.as_p}}#}
            {% for one_obj in page_obj %}
                {{ one_obj }}
                {%  if one_obj.instance.id %}
                        <a class="btn btn-primary mt-1" href="{% url 'caidapp:update_locality' one_obj.instance.id %}">Detail</a>
                        <a class="btn btn-danger mt-1"
                           href="{% url 'caidapp:delete_locality' one_obj.instance.id %}"
                           onclick="return confirm('Delete locality {{ one_obj.instance.name }}: {{ one_obj.instance.visible_name }} ?')">
                        <i class="bi bi-trash"></i></a><br>
                {% endif %}
            {% endfor %}
            <button class="btn btn-primary mt-1" id="btnUpload" type="submit">
                Save
            </button>
            </div>

        </form>
        </section>
    {% endif %}
{%  endblock %}