src/api/CarnivoreIDApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView  # TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("caidapp/", include("caidapp.urls")),
    path("accounts/", include("allauth.urls")),  # <--
    path("accounts/", include("allauth.socialaccount.urls")),  # <--
    path("", RedirectView.as_view(url="/caidapp/")),  # <--I
    # path("", TemplateView.as_view(template_name="caidapp/login.html"), name="login"),  # <--I
]

if settings.DEBUG_TOOLBAR:

    # urlpatterns = [
    #     *urlpatterns,
    # ] + debug_toolbar.debug_toolbar_urls()
    urlpatterns = [
        # path("__debug__/", include(debug_toolbar.urls)),
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    print(f"{urlpatterns=}")

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# print (static(settings.MEDIA_URL))
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/api/caidapp/urls.py
from django.urls import include, path

# from rest_framework import routers
from django.views.generic import DetailView

from . import (
    models,
    views,
    views_admin,
    views_general,
    views_locality,
    views_mediafile,
    views_uploads,
)


def trigger_error(request):
    """Trigger an error for Sentry testing purposes."""
    division_by_zero = 1 / 0
    return division_by_zero


# router = routers.DefaultRouter()
# router.register(r"localities", views.LocalitiesViewSet)


app_name = "caidapp"
urlpatterns = [
    path("", views.login, name="index"),
    path("djangologin/", views.MyLoginView.as_view(), name="djangologin"),
    path("logout/", views.logout_view, name="logout_view"),
    path("user_settings/", views.CaIDUserSettingsView.as_view(), name="update_caiduser"),
    # path("rest_api/", include(router.urls)), # not used any more
    path("workgroup-invitations/create/", views.WorkGroupInvitationCreateView.as_view(), name="workgroup_invitation"),
    path("workgroup-invitations/", views.WorkGroupInvitationListView.as_view(), name="workgroup_invitations"),
    path("workgroup-invitations/for_user/", views.WorkGroupInvitationForUserListView.as_view(), name="workgroup_invitations_for_user"),
    path("workgroup-invitations/<int:pk>/", views.WorkGroupInvitationDetailView.as_view(), name="workgroup_invitation_detail"),
path(
    "workgroup-invitations/<int:pk>/accept/",
    views.WorkGroupInvitationAcceptView.as_view(),
    name="workgroup_invitation_accept",
),

path(
    "workgroup-invitations/<int:pk>/decline/",
    views.WorkGroupInvitationDeclineView.as_view(),
    name="workgroup_invitation_decline",
),

    path("upload/", views.upload_archive, name="upload_archive"),
    # path("user_settings/", views.update_caiduser, name="update_caiduser"),
    path(
        "upload/contains_single_taxon/",
        views.upload_archive,
        {"contains_single_taxon": True},
        name="upload_archive_contains_single_taxon",
    ),
    path(
        "upload/contains_identities/",
        views.upload_archive,
        {"contains_identities": True, "contains_single_taxon": True},
        name="upload_archive_contains_identities",
    ),
    # path("login/", TemplateView.as_view(template_name="caidapp/login.html"), name="login"),
    # Uploads
    path("uploads/", views.uploads_species, name="uploads"),
    path("uploads_identities/", views.uploads_identities, name="uploads_identities"),
    path("uploads_known_identities/", views.uploads_known_identities, name="uploads_known_identities"),
    path(
        "uploadedarchive_mediafiles/<int:uploadedarchive_id>",
        # views.uploadedarchive_mediafiles,
        views.media_files_update,
        name="uploadedarchive_mediafiles",
    ),
    path(
        "uploadedarchive_detail/<int:uploadedarchive_id>",
        # views.uploadedarchive_mediafiles,
        views_uploads.uploadedarchive_detail,
        name="uploadedarchive_detail",
    ),
    # path("media_files/", views.media_files, name="media_files"),
    path(
        "<int:uploadedarchive_id>/delete_upload/<str:next_page>/",
        views.delete_upload,
        name="delete_upload",
    ),
    path(
        "update_uploadedarchive/<int:uploadedarchive_id>/",
        views.update_uploadedarchive,
        name="update_uploadedarchive",
    ),
    path(
        "<int:uploadedarchive_id>/run_processing/",
        views.run_taxon_classification,
        name="run_processing",
    ),
    path(
        "<int:uploadedarchive_id>/run_taxon_classification_force_init/",
        views.run_taxon_classification_force_init,
        name="run_taxon_classification_force_init",
    ),
    path("refresh_data/", views.refresh_data, name="refresh_data"),
    # Localities
    path("manage_localities/", views_locality.manage_localities, name="manage_localities"),
    path("delete_locality/<int:locality_id>/", views_locality.delete_locality, name="delete_locality"),
    path(
        "update_locality/<int:locality_id>/",
        views_locality.update_locality,
        name="update_locality",
    ),
    path(
        "update_locality/",
        views_locality.update_locality,
        name="update_locality",
    ),
    path("taxon/<int:taxon_id>", views.media_files_update, name="taxon"),
    # Media Files
    path("media_files/", views.media_files_update, name="media_files"),
    path(
        "mediafile/<int:pk>/update/",
        views_mediafile.MediaFileUpdateView.as_view(),
        name="media_file_update",
    ),
    # path(
    #     "media_file_update/<int:media_file_id>/",
    #     views_mediafile.media_file_update,
    #     name="media_file_update",
    # ),
    path(
        "media_files/locality/<str:locality_hash>",
        views.media_files_update,
        name="media_files_locality",
    ),
    path(
        "representative_mediafiles/",
        lambda request: views.media_files_update(request, identity_is_representative=True),
        name="representative_mediafiles",
    ),
    path(
        "individual_identity_mediafiles/<int:individual_identity_id>",
        views.media_files_update,
        name="individual_identity_mediafiles",
    ),
    path(
        "delete_mediafile/<int:mediafile_id>/",
        views.delete_mediafile,
        name="delete_mediafile",
    ),
    path(
        "observation/<int:pk>/delete/",
        views_mediafile.ObservationDeleteView.as_view(),
        name="observation_delete",
    ),
    # Albums
    path("albums/", views.albums, name="albums"),
    path("album/<str:album_hash>", views.media_files_update, name="album"),
    path("album_update/<str:album_hash>/", views.album_update, name="album_update"),
    path("delete_album/<str:album_hash>/", views.delete_album, name="delete_album"),
    path("new_album/", views.new_album, name="new_album"),
    # Identity
    path("identities/export_csv", views.export_identities_csv, name="export_identities_csv"),
    path("identities/export_xlsx", views.export_identities_xlsx, name="export_identities_xlsx"),
    path("identities/import", views.import_identities_view, name="import_identities"),
    path(
        "individual_identity_create/",
        views.individual_identity_create,
        name="individual_identity_create",
    ),
    path(
        "individual_identity_create/media_file/<int:media_file_id>",
        views.individual_identity_create,
        name="individual_identity_create",
    ),
    # path(
    #     "individual_identity_update/<int:individual_identity_id>",
    #     views.individual_identity_update,
    #     name="individual_identity_update",
    # ),
    path(
        "individual_identity_update/<int:pk>",
        views.IndividualIdentityUpdateView.as_view(),
        name="individual_identity_update",
    ),
    path(
        "individual_identity/share/<str:identity_hash>",
        views.shared_individual_identity_view,
        name="shared_individual_identity",
    ),
    path(
        "delete_individual_identity/<int:individual_identity_id>",
        views.delete_individual_identity,
        name="delete_individual_identity",
    ),
    # path(
    #     "individual_identities/",
    #     views.individual_identities,
    #     name="individual_identities",
    # ),
    path(
        "individual_identities/",
        views.IdentityListView.as_view(),
        name="individual_identities",
    ),
    path("dash_identities/", views.dash_identities, name="dash_identities"),
    path("init_identification/", views.init_identification_view, name="init_identification"),
    path("train_identification/", views.train_identification, name="train_identification"),
    path("stop_init_identification/", views.stop_init_identification, name="stop_init_identification"),
    path(
        "run_identification/<int:uploadedarchive_id>/",
        views.run_identification_view,
        name="run_identification",
    ),
    path(
        "run_identification_on_unindentified/",
        views.run_identification_on_unidentified,
        name="run_identification_on_unidentified",
    ),
    path(
        "get_individual_identity_zoomed/<int:foridentification_id>/<int:reid_suggestion_id>",
        views.get_individual_identity_zoomed,
        name="get_individual_identity_zoomed",
    ),
    path(
        "get_individual_identity_zoomed_by_identity/<int:foridentification_id>/<int:identity_id>",
        views.get_individual_identity_zoomed_by_identity,
        name="get_individual_identity_zoomed_by_identity",
    ),
    path(
        "get_individual_identity_zoomed_paired_points/<int:foridentification_id>/<int:reid_suggestion_id>",
        views.get_individual_identity_zoomed_paired_points,
        name="get_individual_identity_zoomed_paired_points",
    ),
    path(
        "get_individual_identity/",
        views.get_individual_identity_from_foridentification,
        name="get_individual_identity",
    ),
    path(
        "get_individual_identity/<int:foridentification_id>",
        views.get_individual_identity_from_foridentification,
        name="get_individual_identity",
    ),
    path(
        "get_individual_identity/media_file/<int:media_file_id>",
        views.get_individual_identity_from_foridentification,
        name="get_individual_identity_by_media_file",
    ),
    path(
        "remove_foridentification/<int:foridentification_id>",
        views.remove_foridentification,
        name="remove_foridentification",
    ),
    path(
        "set_individual_identity/" + "<int:mediafiles_for_identification_id>/<int:individual_identity_id>",
        views.set_individual_identity,
        name="set_individual_identity",
    ),
    path(
        "not_identified_mediafiles/",
        views.not_identified_mediafiles,
        name="not_identified_mediafiles",
    ),
    path("show_log/", views.show_log, name="show_log"),
    path("show_taxons/", views.show_taxons, name="show_taxons"),
    # path(
    #     "workgroup_update/<str:workgroup_hash>/",
    #     views.workgroup_update,
    #     name="workgroup_update",

src/api/caidapp/templates/base.html
{% load static %}
{% load custom_filters %}
{% load widget_tweaks %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Wildelife ReID{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'caidapp/anwa.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Bootstrap 5.3 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b3fe7a968a.js" crossorigin="anonymous"></script>

    <!-- Annotorious -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@annotorious/annotorious@latest/dist/annotorious.css">
    <script src="https://cdn.jsdelivr.net/npm/@annotorious/annotorious@latest/dist/annotorious.js"></script>

    <!-- App layout CSS -->
    <link href="{% static 'caidapp/css/layout.css' %}" rel="stylesheet">
    
    <!-- Custom app styles -->
    {% compress css %}
    <link href="{% static 'caidapp/style.css' %}" rel="stylesheet">
    {% endcompress %}

    {% block head %}{% endblock %}
</head>

<body>

<!-- ===================== -->
<!-- NAVBAR               -->
<!-- ===================== -->
<nav class="navbar navbar-dark bg-dark fixed-top px-3 border-bottom mt-0">

    <!-- Mobile toggle -->
    {% if user.is_authenticated %}
    <button class="btn btn-outline-light me-2 d-lg-none" 
            type="button" 
            data-bs-toggle="offcanvas" 
            data-bs-target="#sidebar">
        <i class="bi bi-list"></i>
    </button>

    <!-- Desktop toggle -->
    <button class="btn btn-outline-light me-2 d-none d-lg-inline" 
            id="sidebarToggle" 
            type="button">
        <i class="bi bi-list"></i>
    </button>
    {% endif %}

    <a class="navbar-brand fw-semibold" href="/">Wildlife ReID</a>

    <div class="ms-auto d-flex align-items-center gap-3">
        <button class="btn btn-outline-light"
        onclick="toggleTheme()">
  <i class="bi bi-moon-stars"></i>
</button>
        <a class="nav-link text-light" href="https://mjirik.github.io/CarnivoreID-doc/">
            <i class="bi bi-book"></i>
        </a>
    {%  include 'caidapp/users_menu.html' %}
    </div>
</nav>

<!-- ===================== -->
<!-- APP LAYOUT           -->
<!-- ===================== -->
<div class="app-layout d-flex">

    {% if user.is_authenticated %}
    <!-- SIDEBAR -->
    <div class="offcanvas offcanvas-start d-flex flex-column" id="sidebar" tabindex="-1">
        
        <div class="offcanvas-header d-lg-none">
            <h5 class="offcanvas-title">Menu</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="sidebar-nav flex-grow-1 overflow-y-auto">
            <ul class="nav nav-pills flex-column gap-1 p-2">
                
                <!-- Home -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caidapp:home' %}">
                        <i class="bi bi-house"></i> <span>Home</span>
                    </a>
                </li>

                <!-- Taxon Section -->
                {% if user.caiduser.show_taxon_classification %}
                <li class="nav-item">
                    <a class="nav-link collapsed d-flex align-items-center justify-content-between" 
                       data-bs-toggle="collapse" href="#menu-taxon" role="button" aria-expanded="false">
                       <div class="d-flex align-items-center">
                           <i class="fa-solid fa-hippo"></i> <span>Taxon</span>
                       </div>
                       <i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <div class="collapse" id="menu-taxon">
                        <ul class="nav flex-column ms-3">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:taxon_processing' %}">Processing</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:uploads' %}">Camera Trap Checks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:show_taxons' %}">Taxons</a>
                            </li>
                            {% if user.caiduser.import_dir|length > 0 %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:cloud_import_preview' %}">Cloud Upload</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </li>
                {% endif %}

                <!-- Individuality Section -->
                {% if user.caiduser.workgroup %}
                <li class="nav-item">
                    <a class="nav-link collapsed d-flex align-items-center justify-content-between" 
                       data-bs-toggle="collapse" href="#menu-identity" role="button" aria-expanded="false">
                       <div class="d-flex align-items-center">
                           <i class="fas fa-fingerprint"></i> <span>Individuality</span>
                       </div>
                       <i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <div class="collapse" id="menu-identity">
                        <ul class="nav flex-column ms-3">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:dash_identities' %}">Re-identification</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:uploads_identities' %}">Uploads</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:individual_identities' %}">Identities</a>
                            </li>
                            {% if user.caiduser.workgroup and user.caiduser.workgroup_admin and user.caiduser.show_base_dataset %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'caidapp:uploads_known_identities' %}">Base dataset</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </li>
                {% endif %}

                <!-- Standard Links -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caidapp:media_files' %}">
                        <i class="bi bi-images"></i> <span>Media files</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caidapp:localities' %}">
                        <i class="fa-solid fa-location-pin"></i> <span>Localities</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caidapp:albums' %}">
                        <i class="bi bi-inboxes"></i> <span>Albums</span>
                    </a>
                </li>

                <!-- Admin Section -->
                {% if user.caiduser.workgroup and user.caiduser.workgroup_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caidapp:workgroup-update' user.caiduser.workgroup.id %}">
                        <i class="bi bi-gear"></i> <span>Workgroup Admin</span>
                    </a>
                </li>
                {% endif %}
                
                {% if user.is_staff %}
                <li class="nav-item mt-3">
                    <hr class="my-1">
                    <a class="nav-link" href="{% url 'admin:index' %}">
                        <i class="bi bi-lock"></i> <span>Django Admin</span>
                    </a>
                </li>
                {% endif %}

            </ul>
        </div>

        <!-- Sidebar Footer (Logos) -->
        <div class="sidebar-footer mt-auto p-3 text-center border-top">
            <div class="row g-2 align-items-center">
                <div class="col-6"><img src="{% static 'caidapp/FAV_cmyk_english.png' %}" class="img-fluid" alt="FAV" style="max-height: 40px;"></div>
                <div class="col-6"><img src="{% static 'caidapp/logo_cvut_en.jpg' %}" class="img-fluid" alt="CVUT" style="max-height: 40px;"></div>
                <div class="col-6"><img src="{% static 'caidapp/Mendelu_LDF_logo-ENG_rgb.png' %}" class="img-fluid" alt="Mendelu" style="max-height: 40px;"></div>
                <div class="col-6"><img src="{% static 'caidapp/prostredi_pro_zivot_programme_red.png' %}" class="img-fluid" alt="TACR" style="max-height: 40px;"></div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- CONTENT -->
    <main class="content-wrapper flex-fill p-4">
{#    <div class="container-fluid">#}
        <div id="appbody">
            {% if messages %}
                <div class="alert alert-warning mb-4" role="alert">
                    <ul class="messages mb-0 ps-3">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <!-- Loading Modal -->
            <div class="modal fade" id="loadingModal" tabindex="-1" aria-labelledby="loadingModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="loadingModalLabel">Loading</h5>
                        </div>
                        <div class="modal-body text-center py-4">
                            <div class="spinner-border text-primary mb-3" role="status"></div>
                            <p class="mb-0">Please wait while your request is being processed...</p>
                        </div>
                    </div>
                </div>
            </div>
            {% block body %}{% endblock %}
            {% block content %}{% endblock %}

        </div>
{#    </div>#}
    </main>

</div>

<!-- Scroll to Top -->
<a href="#" class="btn btn-primary rounded-circle position-fixed bottom-0 end-0 m-4 d-flex align-items-center justify-content-center" style="width: 40px; height: 40px; z-index: 1050;" onclick="window.scrollTo({top: 0, behavior: 'smooth'}); return false;">
    <i class="bi bi-arrow-up-short text-white"></i>
</a>

<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>

<!-- Layout Control JS -->
<script src="{% static 'caidapp/js/layout.js' %}"></script>

{% compress js %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Add click event listener to links with the specific class
        document.querySelectorAll('.trigger-loading-modal').forEach(function (link) {
            link.addEventListener('click', function (event) {
                var loadingModal = new bootstrap.Modal(document.getElementById('loadingModal'));
                loadingModal.show();
            });
        });
    });

</script>
{% endcompress %}

{% block script %}{% endblock %}

</body>
</html>